---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/users/{user_id}/posts/{post_id}/comments":
    parameters:
    - name: Auth
      in: header
      required: true
      schema:
        type: string
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    - name: post_id
      in: path
      description: post_id
      required: true
      schema:
        type: string
    get:
      summary: list comments
      responses:
        '200':
          description: successful
    post:
      summary: create comment
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
              required:
              - text
  "/api/users/{user_id}/posts":
    parameters:
    - name: Auth
      in: header
      required: true
      schema:
        type: string
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    get:
      summary: list posts
      responses:
        '200':
          description: successful
  "/api/users":
    get:
      summary: list users
      parameters:
      - name: Auth
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/api/users/{id}":
    parameters:
    - name: Auth
      in: header
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
